server:
  port: 8080
#spring:
#  profiles:
#    active: method_route
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: method_route
#        uri: http://httpbin.org:80/get
#        predicates:
#        - Method=GET
#  profiles: method_route

#spring:
#  profiles:
#    active: elapse_route
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: elapse_route
#        uri: http://httpbin.org:80/get
#        filters:
#        - RequestTime=false
#        predicates:
#        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#  profiles: elapse_route
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: limit_route
#        uri: http://httpbin.org:80/get
#        predicates:
#        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#        filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@hostAddrKeyResolver}'
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 3
#  application:
#    name: gateway-limiter
#  redis:
#    host: localhost
#    port: 6379
#    database: 0


spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: service-hi
        uri: lb://SERVICE-HI
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
          - RequestTime=true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug