server:
  port: 8810

# 关于配置仓库里面文件内容的加密，可以考虑引入http://cloud.spring.io/spring-cloud-vault/
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/allen0224/springcloudConfig/  # 配置git仓库的地址
          searchPaths: myconfig                            # git仓库下的相对地址（多个则用半角逗号分隔）
          # username: username                                  # 只有private的项目才需配置用户名和密码
          # password: password                                  # 只有private的项目才需配置用户名和密码
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka